version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"       # Internal
      - "29092:29092"     # Host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: my-custom-spark-image
    container_name: spark-master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      SPARK_EXTRA_CLASSPATH: /opt/bitnami/spark/jars/external/*

  spark-worker-1:
    image: my-custom-spark-image
    container_name: spark-worker-1
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ~/.ivy2:/root/.ivy2  # ⬅ Mount host's ivy2 to allow JAR caching and live download
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: Worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_EXTRA_CLASSPATH: /opt/bitnami/spark/jars/external/*

  spark-worker-2:
    image: my-custom-spark-image
    container_name: spark-worker-2
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: Worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_EXTRA_CLASSPATH: /opt/bitnami/spark/jars/external/*

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pst_docker
      POSTGRES_PASSWORD: abhi9876
      POSTGRES_DB: kfk_sp_db
    ports:
      - "5433:5432"
